print("This program can launch below applications.")
print("To launch you can command as shown in below example:")
print("Eg:open <application name> for me,launch <application name>,execute <application name> ")
print("  eg: open chrome,launch camera for me")   
print("**************************************************************************************")

print("->chrome")
print("->firefox")
print("->notepad")
print("->windows media player")
print("->explorer")
print("->internet explorer(ie/internet)")
print("->calculator")
print("->paint")
print("->microsoft word")
print("->microsoft powerpoint")
print("->microsoft excel")
print("->adobe reader")
print("->camera")
print("->calendar")
print("->outlook")
print("->microsoft store")
print("->messages")
print("->microsoftedge")
print("->microsoft movies and tv")
print("->microsoft photos")
print("->settings")
print("->vlc media player")
print("->weather")
print("->xbox")
print("->windows defender")
print("->twitter")
print("->facebook")
print("->onenote")
print("->minecraft")
print("->map")
print("->groove music")
print("->candycrush")
print("->alarm and clock")
print("->cortana")
print("->date and time")
print("->pycharm")
print("->jupyter notebook")
print("->python")
print("->recyclebin")
print("->winrar")
print("->vmware")
print("->system information")
print("->task sheduler")
print("->task manager")
print("->firewall")
print("->snipping tool")
print("->control panel")

print("***************************************************************************************")

print("The program can also search your queries on internet via chrome in the following websites:")
print("Eg: google search")
print("    Search for?: apple iphone // will search apple iphone on google")
print("    youtube search")
print("    Search for?: iiec python sessions // searches on youtube")
print("    insta search")
print("    Search for?: iiec // opens iiec page on instagram,you can also search for friend profiles") 
print("    Similarly you can search your favourite products on amazon,flipkart and see cricket scores on cricbuzz")
print("    ask questions on quora....")

print("->google search")
print("->youtube search")
print("->soundcloud search")
print("->wikipedia search")
print("->instagram search")
print("->github search")
print("->amazon search")
print("->flipkart search")
print("->quora search")
print("->cricbuzz")

print("**************************************************************************************")

print("You can play these online games...")

print("->snake arcade")
print("->solitaire")
print("->tic tac toe")
print("->cricket")
print("->tower")
print("*************************************************************************************")
print("You can :")
print("->shutdown")
print("->logoff")
print("->restart  your computer")

print("For more info and examples visit: https://github.com/tejas-mn/-virtual-assistance")