
#using list of programs/files for sorting user input
list=["open","execute","Open","Run","Launch","launch","run","Execute","yes","Yes","how's","my","want","know","How's","play","Play","How","how","take","","Take","download","friend","Friend","wish"]
ng=["dont","Don't","don't","Dont","Not","NOT"]
acc=["yes","Y","y","Yes"]
quit=["bye","later","good bye","quit","see","you","ok"]
conv=["How are you","fine","how","good","Good"]

#list of names of programs and websites

lis=["chrom","Chrome","browser"]
lis1=["firefox","Firefox","browser","Browser","mozilla","Mozilla"]
lis2=["notepad","Notepad","Pad","pad"]
lis3=["windows","Windows"," media","Media", "player","Play","wmplayer","wm","WM"]
lis0=["This","Pc","this","pc","expl","Exp","documents","Documents"]
lis4=["calc","Calc","calculator"]
lis5=["mspaint","Paint","paint","MSpaint"]
lis6=["WINWORD","word","Microsoft","microsoft","Word","msword","MSWORD"]
lis7=["microsoft","point","Power","Point","power","windows","presentation","Presentation","PPT"]
lis8=["excel","Excel","Microsoft","microsoft","MSexcel","EXCEL"]
lis9=["control","Control","Panel","controlpanel","pan","Pan","Con"]
lis10=["iexplor","internet","internet exp","IE","ie","Internet Exp","Iexplorer"]
lis11=["Ado","acrobat","Acrobat","reader","Reader","PDF","acrord32","Acrord32"]
lis12=["shutdown","poweroff","Shut","Off"]
lis13=["logoff","logout","Logout","lock","Lock"]
lis14=["Restart","restart","reboot","Reboot"]
lis15=["PC","device","computer",""]
lis16=["camera","selfie","Cam","Camera","era","capture"]
lis17=["calendar","Calendar","year","month"]
lis18=["outlookmail" ,"mail","outloo","Mail"]
lis19=["ms-windows-store","store","apps","applications"]
lis20=["message","Mess","chat","Chat","messages"]
lis21=["microsoftEdge","edge","Edg","MicrosoftEdge"]
lis22=["msvideo","moviies and tv","Movies","TV","vid","tv","movies","movie"]
lis23=["gallery","phot","Phot","Galler","pictu","Pictures"]
lis24=["settings","Setti","setting","setti"]
lis25=["vlc","VLC"]
lis26=["bingweather","weath","Weather"]
lis27=["xbox","Xbox","XBOX","games"]
lis28=["security","windows security","Security","threat","Virus","antivirus","protec","defend","health of my pc","Health of my PC"]
lis29=["twitter","twitt","tweet","Tweet","Twitter"]
lis30=["onen","Onen","one","Onenote"]
lis31=["minecraft","Minecraft","Craf"]
lis32=["bingmaps","maps","map","location","Map"]
lis33=["mswindowsmusic","Groove","groove","groove music"]
lis34=["candycrushsodasaga","candy","crush","saga"]
lis35=["ms-clock","clock","alarm"]
lis36=["ms-cortana","Cort","corto","Cortana","cortana","cort"]
lis37=["date","time","Time","Date"]
lis38=["pycharm","Pycharm","charm","Charm"]
lis39=["jupyter notebook","book","Jupyter Notebook"]
lis40=["recycle bin","bin","Bin","Recycle"]
lis41=["winrar","WinRAR","Winrar","Rar"]
lis42=["vmware","VM","VMware"]
lis43=["info","msinfo32","system information"]
lis44=["task sheduler","Task Sheduler","sheduler","Shed"]
lis45=["Task manager","task manger","manager","Manager"]
lis46=["Wall","wall"]
lis47=["google search","find","Find","brow"]
lis48=["youtube search","Youtube search","youtube"]
lis49=["soundcloud search","Soundcloud search","soundcl"]
lis50=["screenshot","snipping tool","snip","Snip","Snipping tool","ScreenShot"]
lis51=["wikipedia","wiki","Wikipedia","Wiki"]
lis52=["instagram","Instagram","Insta","insta"]
lis53=["Python","python"]
lis54=["fb","facebook","Facebook"]
lis55=["github","Github","Git","git"]
lis56=["amazon","Amazon"]
lis57=["flipkart","Flipkart"]
lis58=["quora","Quora"]
lis59=["linkedin","Linkedin","linke","Linke"]
lis60=["cricbuzz","Cricbuzz","cricb","Cricb"]

#some games
lis61=["snake","Snake"]
lis62=["solitaire","Solitaire","taire","Taire"]
lis63=["tic","tac","toe","Tic","Tac","Toe"]
lis64=["cricket","Cricket"]
lis65=["tower","Tower"]

#misc
help=["help","Help","guide","Guide"]




